language: dart
sudo: false

os:
  - linux

dart:
  # - stable
  - dev

script:
  - ./tool/travis.sh
  - dart --no-sound-null-safety test/test_all.dart
  - dartfmt -n --set-exit-if-changed lib/ test/
  - dartanalyzer --fatal-warnings --fatal-lints lib/ test/
